import { Accommodation, DestinationSpot, GalleryItem } from './types';

export interface NavLink {
  label: string;
  href: string;
}

export const NAV_LINKS: NavLink[] = [
  { label: 'Home', href: '#' },
  { label: 'Rooms & Villas', href: '#accommodations-section' },
  { label: 'The Retreat', href: '#philosophy' },
  { label: 'Celebrations', href: '#weddings' },
  { label: 'Chronicles', href: '#gallery' },
  { label: 'Around Kelva', href: '#destination-guide' },
  { label: 'FAQs', href: '#faqs' },
  { label: 'Contact', href: '#arrival' },
];

export const ACCOMMODATIONS: Accommodation[] = [
  {
    id: 'garden-view-room',
    category: 'garden',
    title: 'Garden View Room',
    price: '₹5,000',
    originalPrice: '₹7,000',
    discount: 'Save 29%',
    rateSubtitle: 'per night • 380 sq ft • King Size Bed',
    size: '380 sq ft',
    bed: 'King Size Bed',
    capacity: 'Up to 4 Guests',
    unitsAvailable: '2 Units Available',
    description:
      'Spacious room with a private balcony overlooking our lush coconut palm groves and serene gardens.',
    aboutParagraphs: [
      'Immerse yourself in the tranquility of nature in our Garden View Room. Designed with natural textures and a modern coastal palette, this spacious sanctuary features a private verandah that opens directly into our carefully curated palm gardens. Wake up to the gentle rustling of palm leaves and enjoy your morning tea or coffee in a private outdoor setting.',
      'Our spaces are constructed using localized eco-friendly materials and detailed craftsmanship. Large windows let in plenty of natural daylight, while blackout drapes ensure a restful night. High-fidelity fixtures and customized premium bedding invite you to slow down and embrace coastal time.',
    ],
    highlights: ['Private Verandah', 'Garden View', 'Work Desk', 'King Bed'],
    features: [
      'Private Verandah',
      'Garden View',
      'Work Desk',
      'King Bed',
      'Rain Shower',
      'Direct Garden Access',
    ],
    amenities: ['Free WiFi', 'Breakfast', 'AC', 'Private Parking', 'Room Service'],
    moreAmenitiesCount: 1,
    allAmenities: [
      'Free WiFi',
      'Breakfast',
      'AC',
      'Private Parking',
      'Room Service',
      'Tea/Coffee Maker',
    ],
    galleryImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuApaC2PHjDZNAXvC94mxKc2Y9mULXoyhO38tcp5oIMmtmreqljZhffrh26wL9IWQqQdhrrFoLrR7U1qiKBmX2-69HC-aew5xG3UJpY-wfO-LZFp60gEkbk6k-LuOO2FslqqqxSbCsHPUX8nAr6l82gpegrWWV8GWatJG9chfeGP1457iKfRWvByPwL5fj3mG8IHh6Bynin3jtwwCy30tixqZsNdiPphCJ2GyEostURwzUhsEn1vafJf',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1591088398332-8a7791972843?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1200&auto=format&fit=crop',
    ],
    packages: [
      {
        id: 'classic',
        name: 'CLASSIC',
        badge: 'Accommodation',
        subtitle: 'No Food Included',
        pricePerNight: '₹5,000',
        priceUnit: '/ Night',
        roomRateNote: 'Garden View Room ₹5,000',
        extraBedNote: 'Extra Bed ₹500 (up to 4 people)',
        checkIn: '12:00 PM',
        checkOut: '11:00 AM',
        ctaText: 'Book Now',
      },
      {
        id: 'groups',
        name: 'GROUPS',
        badge: 'Per Person Package',
        subtitle: '4 Person Minimum',
        pricePerNight: '₹2,800',
        priceUnit: '/ Per Person',
        roomRateNote: 'Garden View Room ₹2,800 / person',
        mealsIncluded: ['Lunch', 'Hi-Tea', 'Dinner', 'Breakfast'],
        inclusionsNote: '* Includes Resort & Pool Access',
        checkIn: '12:00 PM',
        checkOut: '11:00 AM',
        ctaText: 'Enquire Now',
      },
      {
        id: 'couple',
        name: 'COUPLE',
        badge: 'Couple Package',
        subtitle: 'For 2 Persons',
        pricePerNight: '₹7,000',
        priceUnit: '/ Night',
        roomRateNote: 'Garden View Room ₹7,000',
        mealsIncluded: ['Lunch', 'Hi-Tea', 'Dinner', 'Breakfast'],
        inclusionsNote: '* Includes Resort & Pool Access',
        checkIn: '12:00 PM',
        checkOut: '11:00 AM',
        ctaText: 'Book Now',
      },
    ],
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuApaC2PHjDZNAXvC94mxKc2Y9mULXoyhO38tcp5oIMmtmreqljZhffrh26wL9IWQqQdhrrFoLrR7U1qiKBmX2-69HC-aew5xG3UJpY-wfO-LZFp60gEkbk6k-LuOO2FslqqqxSbCsHPUX8nAr6l82gpegrWWV8GWatJG9chfeGP1457iKfRWvByPwL5fj3mG8IHh6Bynin3jtwwCy30tixqZsNdiPphCJ2GyEostURwzUhsEn1vafJf',
    alt: 'Garden View Room at Beyond Sands with private verandah overlooking lush coconut palm canopy and gardens',
  },
  {
    id: 'pool-view-room',
    category: 'pool',
    title: 'Pool View Room',
    price: '₹5,000',
    originalPrice: '₹8,000',
    discount: 'Save 38%',
    rateSubtitle: 'per night • 400 sq ft • King Size Bed',
    size: '400 sq ft',
    bed: 'King Size Bed',
    capacity: 'Up to 4 Guests',
    unitsAvailable: '4 Units Available',
    description:
      'Stunning room offering direct views of our shimmering infinity pool and the evening pool lights.',
    aboutParagraphs: [
      'Our Pool View Room offers a perfect blend of luxury and convenience. Located just steps away from our azure infinity pool, this room features sliding glass doors that frame beautiful pool views. The interiors are decorated in soothing oceanic blues and warm woods, creating an inviting coastal ambiance. Relax on your private patio or take a refreshing dip at any time.',
      'Our spaces are constructed using localized eco-friendly materials and detailed craftsmanship. Large windows let in plenty of natural daylight, while blackout drapes ensure a restful night. High-fidelity fixtures and customized premium bedding invite you to slow down and embrace coastal time.',
    ],
    highlights: ['Poolside View', 'Direct Pool Access', 'Private Patio', 'King Bed'],
    features: [
      'Poolside View',
      'Direct Pool Access',
      'Private Patio',
      'King Bed',
      'Modern Bath',
      'Evening Turndown',
    ],
    amenities: ['Free WiFi', 'Breakfast', 'AC', 'Pool Access', 'Room Service'],
    moreAmenitiesCount: 2,
    allAmenities: [
      'Free WiFi',
      'Breakfast',
      'AC',
      'Pool Access',
      'Room Service',
      'Spa Access',
      'Tea/Coffee Maker',
    ],
    galleryImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuD6OX__ariicg5oGHm_roWasQ193HsCrGE9-eZDCwqIyu-TE1-nCY7IrX--t2GMqXtzg3BGA6eXVchJNox6QsQvavG8OABrUwbkOKemrHNT46BzZ_btm5XMYxJDU50W5NToQLpu2xiCQyYfoC0rQ_Lun1e-FwwPhLpiV9_9kZQdy3ZEnpagHt4xEQ_RzDxmlIVOJbwXh014EF0ZHBjz2SVeDv87iro0R9Wip8fTL36WkTCfCT8ytf3A',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1200&auto=format&fit=crop',
    ],
    packages: [
      {
        id: 'classic',
        name: 'CLASSIC',
        badge: 'Accommodation',
        subtitle: 'No Food Included',
        pricePerNight: '₹5,000',
        priceUnit: '/ Night',
        roomRateNote: 'Pool View Room ₹5,000',
        extraBedNote: 'Extra Bed ₹500 (up to 4 people)',
        checkIn: '12:00 PM',
        checkOut: '11:00 AM',
        ctaText: 'Book Now',
      },
      {
        id: 'groups',
        name: 'GROUPS',
        badge: 'Per Person Package',
        subtitle: '4 Person Minimum',
        pricePerNight: '₹2,800',
        priceUnit: '/ Per Person',
        roomRateNote: 'Pool View Room ₹2,800 / person',
        mealsIncluded: ['Lunch', 'Hi-Tea', 'Dinner', 'Breakfast'],
        inclusionsNote: '* Includes Resort & Pool Access',
        checkIn: '12:00 PM',
        checkOut: '11:00 AM',
        ctaText: 'Enquire Now',
      },
      {
        id: 'couple',
        name: 'COUPLE',
        badge: 'Couple Package',
        subtitle: 'For 2 Persons',
        pricePerNight: '₹7,000',
        priceUnit: '/ Night',
        roomRateNote: 'Pool View Room ₹7,000',
        mealsIncluded: ['Lunch', 'Hi-Tea', 'Dinner', 'Breakfast'],
        inclusionsNote: '* Includes Resort & Pool Access',
        checkIn: '12:00 PM',
        checkOut: '11:00 AM',
        ctaText: 'Book Now',
      },
    ],
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuD6OX__ariicg5oGHm_roWasQ193HsCrGE9-eZDCwqIyu-TE1-nCY7IrX--t2GMqXtzg3BGA6eXVchJNox6QsQvavG8OABrUwbkOKemrHNT46BzZ_btm5XMYxJDU50W5NToQLpu2xiCQyYfoC0rQ_Lun1e-FwwPhLpiV9_9kZQdy3ZEnpagHt4xEQ_RzDxmlIVOJbwXh014EF0ZHBjz2SVeDv87iro0R9Wip8fTL36WkTCfCT8ytf3A',
    alt: 'Pool View Room offering direct views of shimmering infinity pool and sun patio',
  },
  {
    id: 'couple-room',
    category: 'couples',
    title: 'Couple Room',
    price: '₹4,500',
    originalPrice: '₹9,500',
    discount: 'Save 53%',
    rateSubtitle: 'per night • 350 sq ft • Queen Size Bed',
    size: '350 sq ft',
    bed: 'Queen Size Bed',
    capacity: 'Up to 3 Guests',
    description:
      'Cozy and intimate room specifically designed for couples seeking a romantic coastal escape.',
    aboutParagraphs: [
      'Crafted exclusively for romance, the Couple Room is an intimate sanctuary nestled in a quiet corner of the resort. With soft ambient lighting, premium bedding, and elegant decor, it provides the ultimate setting for honeymoons, anniversaries, or weekend getaways. Enjoy total privacy, modern luxury, and special touches designed to make your stay unforgettable.',
      'Our spaces are constructed using localized eco-friendly materials and detailed craftsmanship. Large windows let in plenty of natural daylight, while blackout drapes ensure a restful night. High-fidelity fixtures and customized premium bedding invite you to slow down and embrace coastal time.',
    ],
    highlights: ['Romantic Setting', 'Premium Bedding', 'Private Balcony', 'Queen Bed'],
    features: [
      'Romantic Setting',
      'Premium Bedding',
      'Private Balcony',
      'Queen Bed',
      'Luxury Bath',
      'Couples Massage Access',
    ],
    amenities: ['Free WiFi', 'Breakfast', 'AC', 'Room Service', 'Romantic Setup'],
    moreAmenitiesCount: 2,
    allAmenities: [
      'Free WiFi',
      'Breakfast',
      'AC',
      'Room Service',
      'Romantic Setup',
      'Spa Access',
      'Welcome Drinks',
    ],
    galleryImages: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCdAgF1EWeA5eeXi83vufemDELokt6cIa-zHur7FIECQztynYBb-Zu5kVWOnVDZqfUNt1_CdI-sbi4jYIthfCAJ3tPSnoMSBhElNiKJ_gY9r85LpJnjTIQuL3WP_g5VnVrY-9zR3dkdEe51iuz_-Oaz3hakF3wTAqnTGMNs-xHuxUL3oRZzBUk97d1DD1FLaaobT83p21aVDdg_IgRqf3Nx9n7tmTGpbvMx63htukBLUVlyGNwGoyt8',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1200&auto=format&fit=crop',
    ],
    packages: [
      {
        id: 'classic',
        name: 'CLASSIC',
        badge: 'Accommodation',
        subtitle: 'No Food Included',
        pricePerNight: '₹4,500',
        priceUnit: '/ Night',
        roomRateNote: 'Couple Room ₹4,500',
        extraBedNote: 'Extra Bed ₹500 (up to 3 people)',
        checkIn: '12:00 PM',
        checkOut: '11:00 AM',
        ctaText: 'Book Now',
      },
      {
        id: 'groups',
        name: 'GROUPS',
        badge: 'Per Person Package',
        subtitle: '3 Person Minimum',
        pricePerNight: '₹2,800',
        priceUnit: '/ Per Person',
        roomRateNote: 'Couple Room ₹2,800 / person',
        mealsIncluded: ['Lunch', 'Hi-Tea', 'Dinner', 'Breakfast'],
        inclusionsNote: '* Includes Resort & Pool Access',
        checkIn: '12:00 PM',
        checkOut: '11:00 AM',
        ctaText: 'Enquire Now',
      },
      {
        id: 'couple',
        name: 'COUPLE',
        badge: 'Couple Package',
        subtitle: 'For 2 Persons',
        pricePerNight: '₹7,000',
        priceUnit: '/ Night',
        roomRateNote: 'Couple Room ₹7,000',
        mealsIncluded: ['Lunch', 'Hi-Tea', 'Dinner', 'Breakfast'],
        inclusionsNote: '* Includes Resort & Pool Access',
        checkIn: '12:00 PM',
        checkOut: '11:00 AM',
        ctaText: 'Book Now',
      },
    ],
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCdAgF1EWeA5eeXi83vufemDELokt6cIa-zHur7FIECQztynYBb-Zu5kVWOnVDZqfUNt1_CdI-sbi4jYIthfCAJ3tPSnoMSBhElNiKJ_gY9r85LpJnjTIQuL3WP_g5VnVrY-9zR3dkdEe51iuz_-Oaz3hakF3wTAqnTGMNs-xHuxUL3oRZzBUk97d1DD1FLaaobT83p21aVDdg_IgRqf3Nx9n7tmTGpbvMx63htukBLUVlyGNwGoyt8',
    alt: 'Couple Room with romantic setting, premium bedding, and private balcony',
  },
  {
    id: 'family-dorm',
    category: 'family',
    title: 'Family Dorm',
    price: '₹6,500',
    originalPrice: '₹14,000',
    discount: 'Save 54%',
    rateSubtitle: 'per night • 650 sq ft • Multiple Beds (2 King + 2 Single)',
    size: '650 sq ft',
    bed: 'Multiple Beds (2 King + 2 Single)',
    capacity: 'Up to 8 Guests',
    description:
      'Spacious multi-bed accommodation perfect for families or groups of friends traveling together.',
    highlights: ['Family Friendly', 'Multiple Beds', 'Spacious Seating', 'Garden View'],
    amenities: ['Free WiFi', 'Breakfast', 'AC', 'Private Parking', 'Room Service'],
    moreAmenitiesCount: 1,
    allAmenities: [
      'Free WiFi',
      'Breakfast',
      'AC',
      'Private Parking',
      'Room Service',
      'Luggage Storage & Lockers',
      'Multiple Power Outlets',
      'Spacious Lounge Seating',
    ],
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCcOPFx_kuzHUMZC6w2Yni7rkNgNwYgVCG5L2hiBFDokGNdp_dCu4vvBKEyEOKN1Uxq74BB_YiI5RmbCjqnXUuGuuHqLkz8-deOm3sPMI5mYVXhljOB9G1qK6dKTZfbLTUTeCuSMI8N5on1dRbl7aPZ4R5bsmbtXEQbBFb3qQRF5bcXnoGPBFjewT5U3044StL33LXuwjWZyAQSICCI62DapkZDWYDzBCxWUHHHsd6AXeyPyU6v1910',
    alt: 'Spacious Family Dorm with multiple beds, warm lighting, and generous lounging space',
  },
  {
    id: 'garden-view-family-room',
    category: 'family',
    title: 'Garden View Family Room',
    price: '₹6,000',
    originalPrice: '₹10,000',
    discount: 'Save 40%',
    rateSubtitle: 'per night • 480 sq ft • Multiple Beds (King + 2 Single)',
    size: '480 sq ft',
    bed: 'Multiple Beds (King + 2 Single)',
    capacity: 'Up to 6 Guests',
    description:
      'A spacious family room surrounded by lush garden views, ideal for families or groups of up to 6 guests.',
    highlights: ['Family Friendly', 'Garden View', 'Multiple Beds', 'Private Verandah'],
    amenities: ['Free WiFi', 'Breakfast', 'AC', 'Private Parking', 'Room Service'],
    moreAmenitiesCount: 2,
    allAmenities: [
      'Free WiFi',
      'Breakfast',
      'AC',
      'Private Parking',
      'Room Service',
      'Wardrobe & Safe',
      'Family Dining Nook',
      'Electric Tea Station',
    ],
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC1GDp5_CaX_3ECMkuyuYpNBYqeA8Q42lZOV_48_3Dveu71NbxOzTcBH0HGjh95vtT5a3Qy7EEV-f4R2VCVMNEgHgQrTeWWTeuDxjZoMsn46YsByNGAN-b0sALODDOJtsu7EJpr6y5gG1jaH7TgeZCaqw9pDICS-0UAJoKFC3kZ3BnwH7JclTy8-T6d9V1eGXBf5NYG4kq5Lc9_kBBbBk-AqCP74eeiHQfUaCPsm77pIlvwxpr4K_D0',
    alt: 'Garden View Family Room surrounded by garden foliage with private verandah and multiple beds',
  },
];

export const DESTINATION_SPOTS: DestinationSpot[] = [
  {
    id: 'kelva-beach',
    title: 'Kelva Beach',
    distance: '5 Min Stroll',
    description:
      'A gentle path winding through Suru pine groves leading right to soft golden shores and low-tide walks.',
    highlight: 'Direct Access',
    icon: 'water',
  },
  {
    id: 'kelva-sea-fort',
    title: 'Kelva Sea Fort',
    distance: '1.5 km Offshore',
    description:
      '16th-century marine outpost reachable on foot during morning low tides. A silent, stoic heritage sentinel.',
    highlight: 'Low-Tide Trek',
    icon: 'fort',
  },
  {
    id: 'kelva-dam',
    title: 'Kelva Dam & Lake',
    distance: '4.5 km Drive',
    description:
      'Serene freshwater reservoir encircled by forested Sahyadri foothills, ideal for meditative dawn bicycling.',
    highlight: 'Bicycle Excursion',
    icon: 'forest',
  },
  {
    id: 'shitaladevi-temple',
    title: 'Shitaladevi Temple',
    distance: '100 Metres',
    description:
      'Centuries-old beachfront shrine located directly opposite the resort sanctuary, echoing with morning sea mantras.',
    highlight: 'Spiritual Neighbor',
    icon: 'temple_hindu',
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'The Plunge Pool at Blue Hour',
    category: 'grounds',
    subtitle: 'Atmosphere',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC1GDp5_CaX_3ECMkuyuYpNBYqeA8Q42lZOV_48_3Dveu71NbxOzTcBH0HGjh95vtT5a3Qy7EEV-f4R2VCVMNEgHgQrTeWWTeuDxjZoMsn46YsByNGAN-b0sALODDOJtsu7EJpr6y5gG1jaH7TgeZCaqw9pDICS-0UAJoKFC3kZ3BnwH7JclTy8-T6d9V1eGXBf5NYG4kq5Lc9_kBBbBk-AqCP74eeiHQfUaCPsm77pIlvwxpr4K_D0',
    alt: 'Reflective saltwater plunge pool surrounded by architectural sandstone pavers and modern minimalist deck loungers in twilight illumination at Beyond Sands Kelva.',
    span: 'sm:col-span-2 lg:col-span-7',
  },
  {
    id: 'gal-2',
    title: 'Linen, Stone & Morning Light',
    category: 'suites',
    subtitle: 'Interiors',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCcOPFx_kuzHUMZC6w2Yni7rkNgNwYgVCG5L2hiBFDokGNdp_dCu4vvBKEyEOKN1Uxq74BB_YiI5RmbCjqnXUuGuuHqLkz8-deOm3sPMI5mYVXhljOB9G1qK6dKTZfbLTUTeCuSMI8N5on1dRbl7aPZ4R5bsmbtXEQbBFb3qQRF5bcXnoGPBFjewT5U3044StL33LXuwjWZyAQSICCI62DapkZDWYDzBCxWUHHHsd6AXeyPyU6v1910',
    alt: 'Close up architectural detail of rumpled Belgian raw linen bed sheets, morning sunbeam casting palm leaf shadows on limestone wall inside a luxury Kelva suite.',
    span: 'sm:col-span-2 lg:col-span-5',
  },
  {
    id: 'gal-3',
    title: 'The Suru & Coconut Grove Walk',
    category: 'grounds',
    subtitle: 'Sanctuary Grounds',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDKUBAePrLk8Gxw-nzELWPvQBOlI3Ueb9EgDGrAAC5JtapJ9m6HBhsS9inOxaJOY7lI06eBFaxQrDw3A3CzJ1YSc6OZXpMx6zryveBWpQM9s7iVUArt54YRV8gUC8mEfr3wVRMAlzI45x2KwMzCHe4nEuiYjXyizojTC_dgidL_o_doem6I1UO8AzVnxK4ImzZnKyWb-aTfw_GJhdfBkq4omTtliknbMO8-ojczbO-Rd2ttt5FqEzy8',
    alt: 'Serene stone pathway winding through a dense natural grove of coconut palms and fragrant frangipani blossoms heading toward the quiet Kelva beachfront.',
    span: 'sm:col-span-2 lg:col-span-5',
  },
  {
    id: 'gal-4',
    title: 'Twilight Communal Banquets',
    category: 'gatherings',
    subtitle: 'Gastronomy',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCZAxuanRWujZaNlr7aAXrgTb2KwnsRkMjKR3Zw8IoeJVAyB9AbvSj-hMFutBw0FJZ3vlb1i7YSdiuPr2mbRdXcSxFnuIhtUIrpXzxx8ib5rNBvQNiMfvVpGTo0vLGH7XlWqpY1ygK-WXEsU6yibFltry7CRVBeQYcU-Le7DsZquys8EmS-MmqBmrr3bCBt7uF3pS7OWnSjhRJxwISNPPe90HqxdLlCEGiBzEocKZEKPOSFEK9_PQey',
    alt: 'An intimate wooden dining table dressed with brass tableware, artisanal ceramic plates, and glowing taper candles arranged under swaying palms for a coastal dinner.',
    span: 'sm:col-span-2 lg:col-span-7',
  },
];
